export const colorChip = [
    { name: 'Blue', hex: '#3498db' },
    { name: 'Mint', hex: '#2ecc71' },
    { name: 'Green', hex: '#27ae60' },
    { name: 'Sage', hex: '#9bcca3' },
    { name: 'Yellow', hex: '#f1c40f' },
    { name: 'Beige', hex: '#f5deb3' },
    { name: 'Brown', hex: '#8b4513' },
    { name: 'Orange', hex: '#e67e22' },
    { name: 'Peach', hex: '#f5b7b1' },
    { name: 'Red', hex: '#e74c3c' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'Pink', hex: '#ff69b4' },
    { name: 'Purple', hex: '#9b59b6' },
    { name: 'Navy', hex: '#2c3e50' },
    { name: 'Black', hex: '#000000' },
    { name: 'Grey', hex: '#bdc3c7' },
    { name: 'White', hex: '#ffffff' },
];

export const collections = [
    'Pastel',
    'Vintage',
    'Retro',
    'Neon',
    'Gold',
    'Light',
    'Dark',
    'Warm',
    'Cold',
    'Summer',
    'Fall',
    'Winter',
    'Spring',
    'Happy',
    'Nature',
    'Earth',
    'Night',
    'Space',
    'Rainbow',
    'Gradient',
    'Sunset',
    'Sky',
    'Sea',
    'Kids',
    'Skin',
    'Food',
    'Cream',
    'Coffee',
    'Wedding',
    'Christmas',
    'Halloween',
];
